version: 2

models:

  - name: stg_orders
    tests:
      - not_null:
          column_name: order_id
      - unique:
          column_name: order_id

  - name: dim_customers
    tests:
      - not_null:
          column_name: customer_id
      - unique:
          column_name: customer_id

  - name: dim_products
    tests:
      - not_null:
          column_name: product_id
      - unique:
          column_name: product_id

  - name: fact_orders
    tests:
      - not_null:
          column_name: order_id
      - unique:
          column_name: order_id
